/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/bells17/common-network-policy-operator/pkg/apis/commonnetworkpolicies/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CommonNetworkPolicyLister helps list CommonNetworkPolicies.
type CommonNetworkPolicyLister interface {
	// List lists all CommonNetworkPolicies in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.CommonNetworkPolicy, err error)
	// Get retrieves the CommonNetworkPolicy from the index for a given name.
	Get(name string) (*v1alpha1.CommonNetworkPolicy, error)
	CommonNetworkPolicyListerExpansion
}

// commonNetworkPolicyLister implements the CommonNetworkPolicyLister interface.
type commonNetworkPolicyLister struct {
	indexer cache.Indexer
}

// NewCommonNetworkPolicyLister returns a new CommonNetworkPolicyLister.
func NewCommonNetworkPolicyLister(indexer cache.Indexer) CommonNetworkPolicyLister {
	return &commonNetworkPolicyLister{indexer: indexer}
}

// List lists all CommonNetworkPolicies in the indexer.
func (s *commonNetworkPolicyLister) List(selector labels.Selector) (ret []*v1alpha1.CommonNetworkPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CommonNetworkPolicy))
	})
	return ret, err
}

// Get retrieves the CommonNetworkPolicy from the index for a given name.
func (s *commonNetworkPolicyLister) Get(name string) (*v1alpha1.CommonNetworkPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("commonnetworkpolicy"), name)
	}
	return obj.(*v1alpha1.CommonNetworkPolicy), nil
}
