apiVersion: commonnetworkpolicies.bells17.io/v1alpha1
kind: CommonNetworkPolicy
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: commonnetworkpolicy-sample
spec:
  # Add fields here
  foo: bar
